title = "Axiomatic Semantics"
description = "Brute force solutions with proofs by intimidation"
base_url = "https://axiomatic.neophilus.net"
default_language = "en"

compile_sass = true
highlight_theme = "charcoal"

generate_feed = true

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true
extra_syntaxes = ["syntaxes"]

[extra.author]
name = "Tim DuBois"
