title = "Axiomatic Semantics"
description = "Brute force solutions with proofs by intimidation"
base_url = "https://axiomatic.neophilus.net"
default_language = "en"

compile_sass = true
highlight_code = true
highlight_theme = "charcoal"
extra_syntaxes = ["syntaxes"]

generate_rss = true

taxonomies = [
    {name = "tags"},
]

[extra.author]
name = "Tim DuBois"
